# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'weather-doll' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Then'
pod 'SnapKit'
pod 'Alamofire'

  # Pods for weather-doll

end
